version: '3'

services:
  web:
    image: buzzingpixel/nginx:latest
    container_name: nginx-buzzingpixel
    ports:
      - "${dockerNginxPort}:80"
    volumes:
      - .:/app
      - ${dockerNginxConfFile}:/etc/nginx/conf.d/site.conf
  php:
    image: buzzingpixel/php7.2:latest
    container_name: php-buzzingpixel
    volumes:
      - .:/app
      - ./serverConfig/php/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini
      - ${dockerPhpEnvIni}:/usr/local/etc/php/conf.d/php-env-config.ini
  db:
    image: buzzingpixel/mariadb:latest
    container_name: db-buzzingpixel
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mySqlRootPassword}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    user: "1000:50"
    volumes:
      - .:/app
      - ${dockerDbDataDir}:/var/lib/mysql
    ports:
      - "${dockerDbPort}:3306"
